fix(ci/cd): fixing ci/cd deployment

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -27,5 +27,6 @@ jobs:
       - name: Build project
         run: yarn build
 
-      - name: Run tests
-        run: yarn test
+      # Add this line to exit with an error code if any step fails
+      - name: Set build status
+        run: exit ${{ job.status }}
